using CheckUP.object1;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace CheckUP.objdb
{
    public class CustCheckUpPatientValueNormalDB
    {
        ConnectDB conn;
        public CustCheckUpPatientValueNormal ccpvn;
        public CustCheckUpPatientValueNormalDB(ConnectDB c)
        {
            conn = c;
            initConfig();
        }
        private void initConfig()
        {
            ccpvn = new CustCheckUpPatientValueNormal();
            ccpvn.Id = "patient_id";
            ccpvn.CustCheckUpId = "cust_checkup_id";
            ccpvn.ChecklistId = "t_checklist_id";
            ccpvn.visitHn = "visit_hn";
            ccpvn.patientFullname = "patient_fullname";
            ccpvn.patientAge = "patient_age";
            ccpvn.departmentName = "department_name";
            ccpvn.pid = "pid";
            ccpvn.patientNumber = "patient_number";
            ccpvn.sectionName = "section_name";
            ccpvn.vitalsign = "vitalsign";
            ccpvn.patientHeight = "patient_height";
            ccpvn.patientPulse = "patient_pulse";
            ccpvn.patientWeight = "patient_weight";
            //ccpvn.EyeShortLongLeft = "eye_short_long_left";
            //ccpvn.EyeShortLongRight = "eye_short_long_right";
            ccpvn.EyedegreeLeft = "eye_degree_left";
            ccpvn.EyeDegreeRight = "eye_degree_right";
            ccpvn.EyeShortLongLeft = "eye_short_long_left";
            ccpvn.EyeShortLongRight = "eye_short_long_right";
            ccpvn.EyeSquintLeft = "eye_squint_left";
            ccpvn.EyeSquintRight = "eye_squint_short";
            ccpvn.EyeOldLeft = "eye_old_left";
            ccpvn.EyeOldRight = "eye_old_right";
            ccpvn.EyeSummary = "eye_summary";
            ccpvn.EyeResult = "eye_result";
            ccpvn.EyeBlindness = "eye_blindness";

            ccpvn.fSexId = "f_sex_id";
            ccpvn.summaryPhysicalExam = "summary_physical_exam";

            ccpvn.stoolExamColor = "stool_exam_color";
            ccpvn.stoolExamAppearance = "stool_exam_appearance";
            ccpvn.stoolExamWbc = "stool_exam_wbc";
            ccpvn.stoolExamRbc = "stool_exam_rbc";
            ccpvn.stoolExamParasite = "stool_exam_parasite";
            ccpvn.stoolExamSummary = "stool_exam_summary";

            //ccpvn.toxicologyLead = "toxicology_lead";
            //ccpvn.toxicologyMercury = "toxicology_mercury";
            //ccpvn.toxicologyBenzene = "toxicology_benzene";
            //ccpvn.toxicologyXylene = "toxicology_xylene";
            ccpvn.Audiogram500L = "audiogram_500_left";
            ccpvn.Audiogram1000L = "audiogram_1000_left";
            ccpvn.Audiogram2000L = "audiogram_2000_left";
            ccpvn.Audiogram3000L = "audiogram_3000_left";
            ccpvn.Audiogram4000L = "audiogram_4000_left";
            ccpvn.Audiogram6000L = "audiogram_6000_left";
            ccpvn.Audiogram8000L = "audiogram_8000_left";
            ccpvn.AudiogramSummaryL = "audiogram_summary_left";
            ccpvn.Audiogram500R = "audiogram_500_right";
            ccpvn.Audiogram1000R = "audiogram_1000_right";
            ccpvn.Audiogram2000R = "audiogram_2000_right";
            ccpvn.Audiogram3000R = "audiogram_3000_right";
            ccpvn.Audiogram4000R = "audiogram_4000_rightt";
            ccpvn.Audiogram6000R = "audiogram_6000_right";
            ccpvn.Audiogram8000R = "audiogram_8000_right";
            ccpvn.AudiogramSummaryR = "audiogram_summary_right";
            ccpvn.AudiogramExam = "audiogram_exam";
            ccpvn.xrayChestExam = "xray_chest_exam";
            ccpvn.xrayChestSummary = "xray_chest_summary";
            ccpvn.eyesExam = "eyes_exam";
            ccpvn.ekgExam = "ekg_exam";
            ccpvn.caAfp = "ca_afp";
            ccpvn.caCea = "ca_cea";
            ccpvn.caPsa = "ca_psa";
            ccpvn.caHcg = "ca_hcg";
            ccpvn.ca153 = "ca_153";
            ccpvn.ca125 = "ca_125";
            ccpvn.ca199 = "ca_19_9";
            ccpvn.thyroidT3 = "thyroid_t3";
            ccpvn.thyroidT4 = "thyroid_t4";
            ccpvn.thyroidTsh = "thyroid_tsh";
            ccpvn.fPatientBloodGroupId = "f_patient_blood_group_id";
            ccpvn.vdrl = "vdrl";
            ccpvn.antiHiv = "anti_hiv";
            ccpvn.hbsag = "hbsag";
            ccpvn.hbsab = "hbsab";
            ccpvn.amphetamine = "amphetamine";
            ccpvn.disscusExam = "disscus_exam";
            ccpvn.suggestExam = "suggest_exam";
            ccpvn.sugar = "sugar";
            ccpvn.sugarDiagnosis = "sugar_diagnosis";
            ccpvn.sugarSummary = "sugar_summary";
            ccpvn.sugarSuggess = "sugar_suggess";
            ccpvn.kidneyBun = "kidney_bun";
            ccpvn.kidneyCreatinine = "kidney_creatinine";
            ccpvn.kidneyResult = "kidney_result";
            ccpvn.kidneySummary = "kidney_summary";
            ccpvn.liverSgot = "liver_sgot";
            ccpvn.liverSgpt = "liver_sgpt";
            ccpvn.liverAlp = "liver_alp";
            ccpvn.liverResult = "liver_result";
            ccpvn.liverSummary = "liver_summary";
            ccpvn.uricAcid = "uric_acid";
            ccpvn.cholesterol = "cholesterol";
            ccpvn.triglyceride = "triglyceride";
            ccpvn.triglycerideResult = "triglyceride_result";
            ccpvn.triglycerideSummary = "triglyceride_summary";
            ccpvn.hdl = "hdl";
            ccpvn.ldl = "ldl";
            ccpvn.calcium = "calcium";
            ccpvn.cbcMcv = "cbc_mcv";
            ccpvn.cbcHb = "cbc_hb";
            ccpvn.cbcHct = "cbc_hct";
            ccpvn.cbcWbc = "cbc_wbc";
            ccpvn.cbcNeutrophil = "cbc_neutrophil";
            ccpvn.cbcLymphocyte = "cbc_lymphocyte";
            ccpvn.cbcEosinophil = "cbc_eosinophil";
            ccpvn.cbcMonocyte = "cbc_monocyte";
            ccpvn.cbcBasophil = "cbc_basophil";
            ccpvn.cbcPlateletCount = "cbc_platelet_count";
            ccpvn.cbcRbcMorpholog = "cbc_rbc_morpholog";
            ccpvn.cbcSummary = "cbc_summary";
            ccpvn.urineColor = "urine_color";
            ccpvn.urineAppearance = "urine_appearance";
            ccpvn.urinePh = "urine_ph";
            ccpvn.urineSpGr = "urine_sp_gr";
            ccpvn.urineSugar = "urine_sugar";
            ccpvn.urineProtein = "urine_protein";
            ccpvn.urineBlood = "urine_blood";
            ccpvn.urineKetone = "urine_ketone";
            ccpvn.urineBacteria = "urine_bacteria";
            ccpvn.urineWbc = "urine_wbc";
            ccpvn.urineRbc = "urine_rbc";
            ccpvn.urineEpithelium = "urine_epithelium";
            ccpvn.urineSummary = "urine_summary";
            ccpvn.urineResult = "urine_result";
            ccpvn.lungFvcPredic = "lung_fvc_predic";
            ccpvn.lungFvcMeas = "lung_fvc_meas";
            ccpvn.lungFvcPer = "lung_fvc_per";
            ccpvn.lungFev1Predic = "lung_fev1_predic";
            ccpvn.lungFev1Meas = "lung_fev1_meas";
            ccpvn.lungFev1Per = "lung_fev1_per";
            ccpvn.lungPerFev1 = "lung_per_fev1";
            ccpvn.lungSummary = "lung_summary";
            ccpvn.lungSuggess = "lung_suggess";
            ccpvn.statusName = "status_name";
            ccpvn.rowNumber = "row_number";

            //ccpvn.cbcMcv="";
            //ccpvn.toxicologyToluene = "toxicology_toluene";

            ccpvn.thyroidRubellaLgg = "thyroid_rubella_lgg";
            ccpvn.billirubin = "billirubin";
            ccpvn.toxicologyThinner = "toxicology_thinner";
            ccpvn.toxicologyAlcohol = "toxicology_alcohol";
            ccpvn.stickerQty = "sticker_qty";
            ccpvn.statusCbc = "status_cbc";
            ccpvn.statusUa = "status_ua";
            ccpvn.statusFbs = "status_fbs";
            ccpvn.statusPe = "status_pe";
            ccpvn.statusXray = "status_xray";
            ccpvn.statusStool = "status_stool";
            ccpvn.statusAntiHiv = "status_anti_hiv";
            ccpvn.statusUricAcid = "status_uric_acid";
            ccpvn.statusAmphetamine = "status_amphetamine";
            ccpvn.statusVisit = "status_visit";
            ccpvn.statusCholes = "status_choles";
            ccpvn.StatusHbsag = "status_hbsag";

            
            ccpvn.cholesterolSummary = "cholesterol_summary";
            ccpvn.cholesterolSuggess = "cholesterol_suggess";

            ccpvn.hbsagSuggess = "hbsag_suggess";
            ccpvn.hbsagSummary = "hbsag_summary";
            ccpvn.cbcRbc = "cbc_rbc";
            ccpvn.cbcMch = "cbc_mch";
            ccpvn.cbcMchc = "cbc_mchc";
            ccpvn.Active = "cust_checkup_patient_active";
            ccpvn.eyeBio = "eye_bio";
            ccpvn.amphetamineSummary = "amphetamine_summary";
            ccpvn.amphetamineSuggess = "amphetamine_suggess";

            ccpvn.antiHivSummary = "anti_hiv_summary";
            ccpvn.antiHivSuggess = "anti_hiv_suggess";
            //ccpvn.eyesExam = "";
            ccpvn.uricAcidSuggess = "uric_acid_suggess";
            ccpvn.uricAcidSummary = "uric_acid_summary";

            ccpvn.visitComment = "visit_comment";
            ccpvn.bmi = "bmi";
            ccpvn.antiHbc = "anti_hbc";
            ccpvn.caFt3 = "ca_ft3";
            ccpvn.hbtyping = "hbtyping";
            //ccpvn.toxicologyHexane = "toxicology_hexane";
            //ccpvn.toxicologyMethanol = "toxicology_methanol";
            //ccpvn.toxicologyMek = "toxicology_mek";
            //ccpvn.toxicologyAcetone = "toxicology_acetone";
            //ccpvn.antiHbc="";
            ccpvn.eyeLeft = "";
            ccpvn.eyeRight = "";
            ccpvn.opticalLeftAngle = "optical_left_angle";
            ccpvn.opticalRightAngle = "optical_right_angle";
            ccpvn.cbcMcvOld = "cbc_mcv_old";
            ccpvn.cbcHbOld = "cbc_hb_old";
            ccpvn.cbcHctOld = "cbc_hct_old";
            ccpvn.cbcWbcOld = "cbc_wbc_old";
            ccpvn.cbcNeutrophilOld = "cbc_neutrophil_old";
            ccpvn.cbcLymphocyteOld = "cbc_lymphocyte_old";
            ccpvn.cbcEosinophilOld = "cbc_eosinophil_old";
            ccpvn.cbcMonocyteOld = "cbc_monocyte_old";
            ccpvn.cbcBasophilOld = "cbc_basophil_old";
            ccpvn.cbcPlateletCountOld = "cbc_platelet_count_old";
            ccpvn.cbcRbcMorphologOld = "cbc_rbc_morpholog_old";
            ccpvn.cbcSummaryOld = "cbc_summary_old";
            ccpvn.cbcRbcOld = "cbc_rbc_old";
            ccpvn.cbcMchcOld = "cbc_mchc_old";
            ccpvn.cbcMchOld = "cbc_mch_old";
            ccpvn.cbcPlateletSmear = "cbc_platelet_smear";
            ccpvn.sugarOld = "sugar_old";
            ccpvn.kidneyBunOld = "kidney_bun_old";
            ccpvn.kidneyCreatinineOld = "kidney_creatinine_old";
            ccpvn.liverSgotOld = "liver_sgot_old";
            ccpvn.liverSgptOld = "liver_sgpt_old";
            ccpvn.liverAlpOld = "liver_alp_old";
            ccpvn.uricAcidOld = "uric_acid_old";
            ccpvn.cholesterolOld = "cholesterol_old";
            ccpvn.triglycerideOld = "triglyceride_old";
            ccpvn.hdlOld = "hdl_old";
            ccpvn.ldlOld = "ldl_old";
            ccpvn.toxicologyLeadOld = "toxicology_lead_old";
            ccpvn.toxicologyMercuryOld = "toxicology_mercury_old";
            ccpvn.toxicologyBenzeneOld = "toxicology_benzene_old";
            ccpvn.toxicologyXyleneOld = "toxicology_xylene_old";
            ccpvn.toxicologyThinnerOld = "toxicology_thinner_old";
            ccpvn.toxicologyAlcoholOld = "toxicology_alcohol_old";
            ccpvn.toxicologyHexaneOld = "toxicology_hexane_old";
            ccpvn.toxicologyMethanolOld = "toxicology_methanol_old";
            ccpvn.toxicologyMekOld = "toxicology_mek_old";
            ccpvn.toxicologyAcetoneOld = "toxicology_acetone_old";
            ccpvn.toxicologyTolueneOld = "toxicology_toluene_old";
            ccpvn.urineLeu = "urine_leu";
            ccpvn.urineOther = "urine_other";
            ccpvn.cultureStool = "culture_stool";
            ccpvn.cultureUrine = "culture_urine";
            ccpvn.cultureBacteria = "culture_bacteria";
            ccpvn.cultureSputum = "culture_sputum";
            ccpvn.marketingCheckupPatientOldId = "marketing_checkup_patient_old_id";
            ccpvn.thyroidFt3 = "thyroid_ft3";
            ccpvn.thyroidFt4 = "thyroid_ft4";
            ccpvn.amylase = "amylase";
            ccpvn.totalProtein = "total_protein";
            ccpvn.albumin = "albumin";
            ccpvn.globulin = "globulin";
            ccpvn.albuminGlobulin = "albumin_globulin";
            ccpvn.directBillirubin = "direct_billirubin";
            ccpvn.colorBlindness = "color_blindness";

            ccpvn.toxiAcetone = "toxicology_acetone";
            ccpvn.toxiAluminium = "toxicology_aluminium";
            ccpvn.toxiAmmonia = "toxicology_ammonia";
            ccpvn.toxiAntimony = "toxicology_antimony";
            ccpvn.toxiArsenic = "toxicology_arsenic";
            ccpvn.toxiBenzene = "toxicology_benzene";
            ccpvn.toxiCadmium = "toxicology_cadmium";
            ccpvn.toxiChromium = "toxicology_chromium";
            ccpvn.toxiCopper = "toxicology_copper";
            ccpvn.toxiEthanol = "toxicology_ethanol";
            ccpvn.toxiFluoride = "toxicology_fluoride";
            ccpvn.toxiFomaldehyde = "toxicology_fomaldehyde";
            ccpvn.toxiHexane = "toxicology_hexane";
            ccpvn.toxiHippuric = "toxicology_hippuric";
            ccpvn.toxiIPA = "toxicology_ipa";
            ccpvn.toxiKetone = "toxicology_ketone";
            ccpvn.toxiLead = "toxicology_lead";
            ccpvn.toxiMandelic = "toxicology_mandelic";
            ccpvn.toxiManganese = "toxicology_manganese";
            ccpvn.toxiMercury = "toxicology_mercury";
            ccpvn.toxiMethanol = "toxicology_methanol";
            ccpvn.toxiMethyl = "toxicology_methyl";
            ccpvn.toxiNickel = "toxicology_nickel";
            ccpvn.toxiPhenol = "toxicology_phenol";
            ccpvn.toxiTin = "toxicology_tin";
            ccpvn.toxiTrichloroethylene = "toxicology_trichloroethylenel";
            ccpvn.toxiZinc = "toxicology_zinc";

            ccpvn.pkField = "patient_id";
            ccpvn.table = "b_cust_checkup_patient_value_normal";
        }
        public DataTable selectByPk()
        {
            String sql = "";
            DataTable dt = new DataTable();
            sql = "Select * From " + ccpvn.table + " ";
            dt = conn.selectData(sql);

            return dt;
        }
    }
}
